name: focus-notes-lite # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Focus Notes Studio
summary: Unleash your creativity with digital painting tools.
description: A sleek and minimal note-taking app with tagging, autosave, and markdown support. Great for journaling, meeting notes, or brainstorming sessions.
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  focus-notes-lite:
    command: bin/focus-notes-lite-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  focus-notes-lite:
    plugin: dump
    source: .
    organize:
      focus-notes-lite-bin: bin/
